### ISSUE TITLE
Missing README ?

### ISSUE THREAD

**Issue by teolemon** [intellisense/django-joyride#4]
It seems that a README might be missing or not in the right place?

pierreslam$ pip install django-joyride
Downloading/unpacking django-joyride
  Downloading django-joyride-0.1.0.tar.gz (99kB): 99kB downloaded
  Running setup.py egg_info for package django-joyride
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/var/folders/kt/pk3qg6_s06x_7sf2rmb_22yr0000gp/T/pip-build/django-joyride/setup.py", line 4, in <module>
        open('CHANGES.rst').read() +
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/var/folders/kt/pk3qg6_s06x_7sf2rmb_22yr0000gp/T/pip-build/django-joyride/setup.py", line 4, in <module>

    open('CHANGES.rst').read() +

IOError: [Errno 2] No such file or directory: 'README.md'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /var/folders/kt/pk3qg6_s06x_7sf2rmb_22yr0000gp/T/pip-build/django-joyride

**Comment by intellisense** [comment]
Thanks for reporting it. This should work now. Released 0.1.2.
